# Preload wallpaper ke RAM
preload = ~/Pictures/Wallpapers/Anime-City-Night.png

# Set wallpaper untuk monitor eDP-1
wallpaper = eDP-1, ~/Pictures/Wallpapers/Anime-City-Night.png

# Aktifkan IPC biar bisa dikontrol via terminal
ipc = true